### ISSUE TITLE
"Open File" file dialog crashes app in latest build

### ISSUE THREAD

**Issue by softwarelifecycle** [gyroflow/gyroflow#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.3.0 (gh836)

### What operating system are you using?

Ubuntu 22.04.1 LTS

### What GPU are you using?

NVIDIA GeForce RTX 2070 Rev. A

### What happened?

- Installed the latest nightly build 1.3.0 (gh836)
- Clicked on Open File button
- Immediately crashed
![GyroflowCrash](https://user-images.githubusercontent.com/44659478/200722180-a0110b06-e9ae-4c2d-901c-147c623c97c4.png)
It does open up the file if dragged onto the UI

**Comment by AdrianEddy** [comment]
Looks like an issue in GTK: https://www.google.com/search?q=filechooser+does+not+contain+%22show-type-column%22
did it work in previous gyroflow version?

**Comment by AdrianEddy** [comment]
Is this AppImage or .tar.gz?

**Comment by AdrianEddy** [comment]
I believe this is fixed in latest dev build https://gyroflow.xyz/devbuild/?autodownload

**Comment by softwarelifecycle** [comment]
It was in the Appimage.. that's been the one that worked the best... I never saw it work... trying out now the new version...

**Comment by softwarelifecycle** [comment]
ok, the latest build fixes the open dialog bug! :)   Thanks very much!
Still getting the green screen... Adding comment there...
